from django.urls import path
from . import views

urlpatterns = [
    path('', views.song, name='song'),
    path('podcastlist', views.podcast, name='podcast'),
    path('audiobooklist', views.audiobook, name='audiobook'),
    path('songupdate/<str:pk>', views.songupdateform, name='songupdateform'),
    path('podcastupdate/<str:pk>', views.podcastupdateform,
         name='podcastupdateform'),
    path('audiobookupdate/<str:pk>', views.audiobookupdateform,
         name='audiobookupdateform'),
    path('songdelete/<str:pk>', views.songdeleteform, name='songdeleteform'),
    path('podcastdelete/<str:pk>', views.podcastdeleteform,
         name='podcastdeleteform'),
    path('audiobookdelete/<str:pk>', views.audiobookdeleteform,
         name='audiobookdeleteform'),
    path('song', views.songlist, name='songlist'),
    path('podcast', views.podcastlist, name='podcastlist'),
    path('audiobook', views.audiobooklist, name='audiobooklist'),
    path('song/<str:pk>', views.songdetail, name='songdetail'),
    path('podcast/<str:pk>', views.podcastdetail, name='podcastdetail'),
    path('audiobook/<str:pk>', views.audiobookdetail, name='audiobookdetail'),
    path('create/song', views.songcreate, name='songcreate'),
    path('create/podcast', views.podcastcreate, name='podcastcreate'),
    path('create/audiobook', views.audiobookcreate, name='audiobookcreate'),
    path('update/song/<str:pk>', views.songupdate, name='songupdate'),
    path('update/podcast/<str:pk>', views.podcastupdate, name='podcastupdate'),
    path('update/audiobook/<str:pk>',
         views.audiobookupdate, name='audiobookupdate'),
    path('delete/song/<str:pk>', views.songdelete, name='songupdelete'),
    path('delete/podcast/<str:pk>', views.podcastdelete, name='podcastdelete'),
    path('delete/audiobook/<str:pk>',
         views.audiobookdelete, name='audiobookdelete'),
]
