# Generated by Django 3.2 on 2021-05-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podcase',
            new_name='Podcast',
        ),
    ]
